-- Migration: Enable Row Level Security (RLS) on all public schema tables
-- This ensures Supabase's auto-generated REST API (PostgREST) exposes zero data by default without policies.
-- Prisma connects as postgres / superuser / table owner and bypasses RLS unhindered.

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Purity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Category" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkStatus" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Customer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Supplier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "GoldStock" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StoneItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StockMovement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StockAdjustment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Sale" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SaleItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalesReturn" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Purchase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PurchaseItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OldGoldExchange" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Workflow" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkflowStep" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkOrder" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkOrderStep" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WastageRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "QualityCheck" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AppNotification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ShopSetting" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SequenceCounter" ENABLE ROW LEVEL SECURITY;
